version: '3'
services:
  rails_test_api:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: sh /app/docker/bin/wait_for_mysql.sh sh /app/docker/bin/rails_start.sh
    ports:
      - 3000:3000
    volumes:
      - .:/app
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_HOST=mysql
      - DOCKER_HOST=0.0.0.0
    depends_on:
      - mysql
  mysql:
    image: mysql:5.6
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

volumes:
  mysql-data:
